.TH RUSTART "1" "" "russ 6.x" ""
.SH NAME
rustart \- Start a RUSS server

.SH SYNOPSIS
.B rustart
.RB [<option>]
.I "(-f <path>|-c <name>=<value>) [...] [-- ...]"

.SH DESCRIPTION
.PP
rustart starts a RUSS server. The configuration file and settings
are used to set up a socket file, start the server, and pass it a
listener socket, and otherwise set things up. Arguments after the
-- are passed to the server untouched.

.PP
Where:
.TP
.B -c <name>=<value>
Set an attribute. The name is composed of a section name and an
attribute name separated by a ":" (e.g., main:addr=+/debug).

.TP
.B -f <path>
Load a configuration file.

.SH CONFIGURATION
.PP
The configuration file uses an INI-style with multiple sections
containing simple name=value attributes.

Only the main section is used by rustart. Supported attributes
are:

.SS Basic main Section Attributes

.TP
.B addr=<address>
Path to the socket file. RUSS-specific aliases such as + and ++
are supported.

.TP
.B file_group=gid|groupname
Group ownership for the socket file. Default is to use the gid of
the user calling rustart.

.TP
.B file_mode=<mode>
File mode for the socket file. Octal mode values must be preceded
by 0 (e.g., 0700).

.TP
.B file_user=uid|username
User ownership for the socket file. Default is to use the uid of
the user calling rustart.

.TP
.B group=gid|groupname
The group under which the server should run. Default is that of the
calling user. Be very careful.

.TP
.B path=<server path>
Path to the server executable to be started.

.TP
.B user=uid|username
The user under which the server should run. Default is that of the
calling user. Be very careful.

.SS Other main Section Attributes

.SH EXAMPLE

.PP
The debug.conf file typically looks like:

.RS
.nf
[main]
path=/usr/lib/russng/russdebug_server
addr=/+/debug
file_mode=0777
.fi
.RE

.PP
Depending on the server, additional sections may be used/required.

.SH AUTHOR
Written by John Marshall.

.SH "REPORTING BUGS"
See contact information at https://expl.info/display/RUSS .

.SH COPYRIGHT
Copyright \(co 2014 John Marshall.
.br
Unless otherwise indicated, this software is available under the
terms of the 
ls
Apache License version 2.