#! /bin/bash
#
# srelay

CONF_FILENAME=/etc/russ/conf/srelay.conf
PID_FILENAME=/var/run/russ/srelay.pid

case $1 in
check)
	[ -f ${CONF_FILENAME} ] && exit $?
	;;
restart)
	$0 stop && sleep 1 && $0 start
	;;
status)
	PID=`cat "${PID_FILENAME}" 2> /dev/null` && `kill -0 ${PID} 2> /dev/null`
	if [ $? = 0 ]; then
		echo "running"
	else
		echo "not running"
	fi
	;;
start)
	PID=`cat "${PID_FILENAME}" 2> /dev/null` && `kill -0 ${PID} 2> /dev/null`
	if [ $? = 0 ]; then
		echo "already running"
		exit 1
	fi
	rusrv_srelay -f ${CONF_FILENAME} < /dev/null > /dev/null 2>&1 &
	echo $! > "${PID_FILENAME}"
	;;
stop)
	PID=`cat "${PID_FILENAME}" 2> /dev/null`
	if [ $? = 0 ]; then
		kill ${PID} 2> /dev/null
		rm -f "${PID_FILENAME}" 2> /dev/null
	fi
	;;
*)
	echo "usage: srelay {start|stop|restart|status}"
	exit 1
	;;
esac
