#! /bin/bash
#
# russtee
#
### BEGIN INIT INFO
# Provides:          russtee
# Required-Start:    $syslog $time $russ
# Required-Stop:     $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: russtee services
# Description:       russtee services
### END INIT INFO

SCRIPT_FILENAME=russtee
SERVER_NAME=tee
ETC_DIR=/etc/russ
RUN_DIR=/var/run/russ
CONF_FILENAME=${ETC_DIR}/conf/${SERVER_NAME}.conf
PID_FILENAME=${RUN_DIR}/${SERVER_NAME}.pid

case $1 in
check)
	[ -f ${CONF_FILENAME} ] && exit $?
	;;
restart)
	$0 stop && sleep 1 && $0 start
	;;
status)
	PID=`cat "${PID_FILENAME}" 2> /dev/null` && `kill -0 ${PID} 2> /dev/null`
	if [ $? = 0 ]; then
		echo "running"
	else
		echo "not running"
	fi
	;;
start)
	/etc/init.d/russ start
	PID=`cat "${PID_FILENAME}" 2> /dev/null` && `kill -0 ${PID} 2> /dev/null`
	if [ $? = 0 ]; then
		echo "already running"
		exit 1
	fi
	rusrv_${SERVER_NAME} -f ${CONF_FILENAME} < /dev/null > /dev/null 2>&1 &
	echo $! > "${PID_FILENAME}"
	;;
stop)
	PID=`cat "${PID_FILENAME}" 2> /dev/null`
	if [ $? = 0 ]; then
		kill ${PID} 2> /dev/null
		rm -f "${PID_FILENAME}" 2> /dev/null
	fi
	;;
*)
	echo "usage: ${SCRIPT_FILENAME} {start|stop|restart|status}"
	exit 1
	;;
esac
