#! /bin/bash
#
# russproc
#
### BEGIN INIT INFO
# Provides:          russproc
# Required-Start:    $syslog $time $russ
# Required-Stop:     $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: russproc services
# Description:       russproc services
### END INIT INFO

SCRIPT_FILENAME=russproc
SERVER_NAME=proc
ETC_DIR=/etc/russ
RUN_DIR=/var/run/russ
CONF_FILENAME=${ETC_DIR}/conf/${SERVER_NAME}.conf
PID_FILENAME=${RUN_DIR}/${SERVER_NAME}.pid

case $1 in
check)
	[ -f ${CONF_FILENAME} ] && exit $?
	;;
restart)
	$0 stop && sleep 1 && $0 start
	;;
status)
	PID=`cat "${PID_FILENAME}" 2> /dev/null` && `kill -0 ${PID} 2> /dev/null`
	if [ $? = 0 ]; then
		echo "running"
	else
		echo "not running"
	fi
	;;
start)
	/etc/init.d/russ start > /dev/null
	echo -n "starting server (${SERVER_NAME}) ... "
	PID=`cat "${PID_FILENAME}" 2> /dev/null` && `kill -0 ${PID} 2> /dev/null`
	if [ $? = 0 ]; then
		echo "RUNNING"
		exit 1
	fi
	rusrv_${SERVER_NAME} -f ${CONF_FILENAME} < /dev/null > /dev/null 2>&1 & pid=$!
	echo ${pid} > "${PID_FILENAME}"
	kill -0 ${pid} && echo "OK" || { echo "FAILED"; exit 1; }
	;;
stop)
	echo -n "stopping server (${SERVER_NAME}) ... "
	PID=`cat "${PID_FILENAME}" 2> /dev/null`
	if [ $? != 0 ]; then
		echo "NOT RUNNING"
		exit 0
	fi
	kill ${PID} 2> /dev/null
	[ $? -eq 0 ] && echo "OK" || echo "FAILED"
	rm -f "${PID_FILENAME}" 2> /dev/null
	;;
*)
	echo "usage: ${SCRIPT_FILENAME} {start|stop|restart|status}"
	exit 1
	;;
esac
