#! /bin/bash
#
# ssh

PID_FILENAME=/var/run/russ/ssh.pid

case $1 in
restart)
	$0 stop && sleep 1 && $0 start
	;;
status)
	PID=`cat "${PID_FILENAME}" 2> /dev/null` && `kill -0 ${PID} 2> /dev/null`
	if [ $? = 0 ]; then
		echo "running"
	else
		echo "not running"
	fi
	;;
start)
	PID=`cat "${PID_FILENAME}" 2> /dev/null` && `kill -0 ${PID} 2> /dev/null`
	if [ $? = 0 ]; then
		echo "already running"
		exit 1
	fi
	rusrv_ssh -f /etc/russ/conf/ssh.conf < /dev/null > /dev/null 2>&1 &
	echo $! > "${PID_FILENAME}"
	;;
stop)
	PID=`cat "${PID_FILENAME}" 2> /dev/null`
	if [ $? = 0 ]; then
		kill ${PID} 2> /dev/null
		rm -f "${PID_FILENAME}" 2> /dev/null
	fi
	;;
*)
	echo "usage: ssh {start|stop|restart|status}"
	exit 1
	;;
esac
