#!/bin/sh
#
# Setup for russ-based services.
#
### BEGIN INIT INFO
# Provides:          russ
# Required-Start:    $syslog $time
# Required-Stop:     $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Sets up for russ-based services
# Description:       Sets up for russ-based services
### END INIT INFO

PLUS_CONF_FILE="/etc/russ/conf/plus.conf"
RUN_DIR="/var/run/russ"
RUBB_SOURCES_FILE="/etc/russ/bb.sources"

start() {
	# ensure working directories
	mkdir -m 0755 -p "${RUN_DIR}"
	mkdir -m 0755 -p "${RUN_DIR}/conf"
	mkdir -m 0755 -p "${RUN_DIR}/pids"
	mkdir -m 0755 -p "${RUN_DIR}/services"

	# load configuration
	if [ ! -e "${RUBB_SOURCES_FILE}" ]; then
		# likely a new install of v7
		echo "setting up for v7 ..." 1>&2

		echo "installing default bb.sources ..." 1>&2
		cp /etc/russ/samples/rubb.sources "${RUBB_SOURCES_FILE}"
		if [ ! -e "${PLUS_CONF_FILE}" ]; then
			echo "installing plus.conf ..." 1>&2
			cp /etc/russ/samples/conf/plus.conf "${PLUS_CONF_FILE}"
		fi
	fi
	[ -e "${RUBB_SOURCES_FILE}" ] && rubb resync

	# start services
	rubb start
}

stop() {
	rubb stop
}

case "$1" in
restart)
	stop
	sleep 1
	start
	;;
start)
	start
	;;
status)
	rubb status
	;;
stop)
	stop
	;;
*)
	echo "Usage: /etc/init.d/russ start|stop|restart|status"
	exit 2
	;;
esac
exit 0
