#!/bin/sh
#
# Setup for russ-based services.
#
### BEGIN INIT INFO
# Provides:          russ
# Required-Start:    $syslog $time
# Required-Stop:     $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Sets up for russ-based services
# Description:       Sets up for russ-based services
### END INIT INFO

RUN_DIR="/var/run/russ"

case "$1" in
start)
	echo "Setup for standard russ servers"
	mkdir -m 0755 -p "${RUN_DIR}"
	mkdir -m 0755 -p "${RUN_DIR}/services"
	;;
stop)
	;;
*)
	echo "Usage: /etc/init.d/russ start"
	exit 2
	;;
esac
exit 0
